name: app_abou_alnour
description: MSN Care Tracker (clean)
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  web_socket_channel: ^2.4.0
  intl: ^0.19.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
