name: Android APK (Debug)
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      # توليد/إعادة توليد مشروع Flutter (اسم باكدج صالح)
      - name: Clean & bootstrap Android
        run: |
          rm -rf android ios web linux windows macos .dart_tool build || true
          flutter create --project-name app_abou_alnour --org com.msncare --platforms android --overwrite .

      - name: Build Debug APK
        run: flutter build apk --debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: build/app/outputs/flutter-apk/app-debug.apk
