name: Android APK (Debug)

on:
  workflow_dispatch:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Flutter (stable 3.22.2)
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2'
          channel: 'stable'

      - name: Versions
        run: |
          flutter --version
          dart --version

      # إعادة توليد مجلد android من الصفر + pub get
      - name: Clean & bootstrap Android
        run: |
          rm -rf android ios macos linux windows web
          flutter create --project-name app_abou_alnour --org com.msncare --platforms android --overwrite .
          flutter pub get

      - name: Build Debug APK
        run: flutter build apk --debug --no-tree-shake-icons -v

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: build/app/outputs/flutter-apk/app-debug.apk
          if-no-files-found: error
