name: Android APK (Debug)
on: { workflow_dispatch: {} }
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Bootstrap Flutter project
        run: |
          flutter pub get
          # لو android مش موجود، أنشئه تلقائيًا
          if [ ! -d android ]; then flutter create .; fi
      - name: Build Debug APK
        run: flutter build apk --debug
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: build/app/outputs/flutter-apk/app-debug.apk
