- name: Ensure Android platform + INTERNET
  run: |
    flutter --version
    if [ ! -f pubspec.yaml ]; then
      echo "pubspec.yaml missing"; exit 1
    fi
    if [ ! -d android ]; then
      flutter create --platforms=android .
    fi
    MANIFEST="android/app/src/main/AndroidManifest.xml"
    if [ -f "$MANIFEST" ] && ! grep -q 'android.permission.INTERNET' "$MANIFEST"; then
      sed -i 's#<application#<uses-permission android:name="android.permission.INTERNET"/>\n    <application#' "$MANIFEST"
    fi
