name: Android APK (Debug)
on: { workflow_dispatch: {}, push: { branches: [ main, master ] } }
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with: { channel: stable }
      - name: Ensure Android platform
        run: |
          if [ ! -d android ]; then flutter create . --platforms=android; fi
      - name: Ensure INTERNET permission
        run: |
          MANIFEST="android/app/src/main/AndroidManifest.xml"
          grep -q 'android.permission.INTERNET' "$MANIFEST" || sed -i '1a <uses-permission android:name="android.permission.INTERNET"/>' "$MANIFEST"
      - run: flutter pub get
      - run: flutter build apk --debug
      - uses: actions/upload-artifact@v4
        with: { name: app-debug, path: build/app/outputs/flutter-apk/app-debug.apk }